import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation objects
const translations = {
  en: {
    // Authentication
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.organization': 'Organization',
    'auth.welcomeBack': 'Welcome Back',
    'auth.createAccount': 'Create Account',
    'auth.signInToAccount': 'Sign in to your account',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.rememberMe': 'Remember me',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.courses': 'Courses',
    'nav.students': 'Students',
    'nav.analytics': 'Analytics',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'nav.organization': 'Organization',
    'nav.contentAnalysis': 'Content Analysis',
    'nav.quizCreator': 'Quiz Creator',
    'nav.questionBank': 'Question Bank',
    'nav.courseManagement': 'Course Management',
    'nav.myCourses': 'My Courses',
    'nav.courseDiscovery': 'Course Discovery',
    'nav.submissions': 'Submissions & Assignments',
    'nav.quizResults': 'Quiz Results',
    'nav.achievements': 'Achievements',
    'nav.cart': 'Shopping Cart',
    'nav.takeQuiz': 'Take Quiz',
    'nav.analytics': 'Learning Analytics',
    'nav.studyTools': 'Study Tools',
    'nav.forums': 'Discussion Forums',
    'nav.certificates': 'Certificates',
    'nav.instructorAnalytics': 'Advanced Analytics',
    'nav.gradebook': 'Gradebook & Assessment',
    'nav.communicationHub': 'Communication Hub',
    'nav.contentAuthoring': 'Content Authoring',
    'nav.platformAnalytics': 'Platform Analytics',
    'nav.userAccessManagement': 'User & Access Management',
    'nav.systemAdministration': 'System Administration',
    'nav.platformConfiguration': 'Platform Configuration',
    'nav.aiTutoring': 'AI Tutoring System',
    'nav.aiEssayGrading': 'AI Essay Grading',
    'nav.aiRecommendations': 'AI Recommendations',
    'nav.aiCredits': 'AI Credits Management',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.language': 'Language',
    'common.by': 'By',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to CogneraX Learn',
    'dashboard.totalStudents': 'Total Students',
    'dashboard.activeCourses': 'Active Courses',
    'dashboard.completionRate': 'Completion Rate',
    'dashboard.aiCredits': 'AI Credits',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.overview': 'Overview',
    'dashboard.analytics': 'Analytics',
    
    // Courses
    'courses.createCourse': 'Create Course',
    'courses.manageCourses': 'Manage Courses',
    'courses.enrolledCourses': 'Enrolled Courses',
    'courses.availableCourses': 'Available Courses',
    'courses.courseName': 'Course Name',
    'courses.courseDescription': 'Course Description',
    'courses.instructor': 'Instructor',
    'courses.duration': 'Duration',
    'courses.difficulty': 'Difficulty',
    'courses.enrolled': 'Enrolled',
    'courses.completed': 'Completed',
    'courses.inProgress': 'In Progress',
    'courses.notStarted': 'Not Started',
    
    // Achievements
    'achievements.title': 'Achievements',
    'achievements.description': 'Track your learning milestones and unlock achievements as you progress through your educational journey.',
    'achievements.totalPoints': 'Total Points',
    'achievements.earned': 'Earned',
    'achievements.pending': 'Pending',
    'achievements.completion': 'Completion',
    'achievements.allAchievements': 'All Achievements',
    'achievements.earnedAchievements': 'Earned Achievements',
    'achievements.pendingAchievements': 'Pending Achievements',
    'achievements.progress': 'Progress',
    'achievements.requirements': 'Requirements',
    'achievements.earnedOn': 'Earned on',
    'achievements.points': 'points',
    'achievements.leaderboard': 'Achievement Leaderboard',
    'achievements.viewLeaderboard': 'View Full Leaderboard',
    'achievements.rank': 'Rank',
    
    // AI Credits
    'aiCredits.title': 'AI Credits',
    'aiCredits.available': 'Available Credits',
    'aiCredits.used': 'Used Credits',
    'aiCredits.remaining': 'Remaining Credits',
    'aiCredits.distribute': 'Distribute Credits',
    'aiCredits.usage': 'Usage',
    
    // Settings
    'settings.general': 'General Settings',
    'settings.profile': 'Profile Settings',
    'settings.security': 'Security Settings',
    'settings.notifications': 'Notification Settings',
    'settings.language': 'Language Settings',
    'settings.theme': 'Theme Settings',
    
    // Errors and Messages
    'error.somethingWentWrong': 'Something went wrong',
    'error.networkError': 'Network error occurred',
    'error.invalidCredentials': 'Invalid credentials',
    'success.loginSuccess': 'Login successful',
    'success.signupSuccess': 'Account created successfully',
    'success.saveSuccess': 'Changes saved successfully',
    'success.deleteSuccess': 'Item deleted successfully',
    
    // Time and Dates
    'time.today': 'Today',
    'time.yesterday': 'Yesterday',
    'time.thisWeek': 'This Week',
    'time.thisMonth': 'This Month',
    'time.minute': 'minute',
    'time.minutes': 'minutes',
    'time.hour': 'hour',
    'time.hours': 'hours',
    'time.day': 'day',
    'time.days': 'days',
    'time.week': 'week',
    'time.weeks': 'weeks',
    'time.month': 'month',
    'time.months': 'months',
    'time.year': 'year',
    'time.years': 'years',
    
    // Cart
    'cart.title': 'Shopping Cart',
    'cart.subtitle': 'Review and purchase your selected courses',
    'cart.emptyTitle': 'Your cart is empty',
    'cart.emptyDescription': 'Browse our course catalog and add courses to your cart to get started.',
    'cart.browseCourses': 'Browse Courses',
    'cart.clearCart': 'Clear Cart',
    'cart.orderSummary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.tax': 'Tax',
    'cart.total': 'Total',
    'cart.proceedToCheckout': 'Proceed to Checkout',
    'cart.checkout': 'Checkout',
    'cart.addedToCart': 'Course added to cart',
    'cart.removedFromCart': 'Course removed from cart',
    
    // Student Analytics
    'Learning Analytics': 'Learning Analytics',
    'Track your progress and optimize your learning journey': 'Track your progress and optimize your learning journey',
    'Total Study Hours': 'Total Study Hours',
    'Average Score': 'Average Score',
    'Learning Streak': 'Learning Streak',
    'Achievements': 'Achievements',
    'Weekly Learning Hours': 'Weekly Learning Hours',
    'Quiz Performance Trend': 'Quiz Performance Trend',
    'Course Progress': 'Course Progress',
    'Skill Assessment': 'Skill Assessment',
    'Skill Development Progress': 'Skill Development Progress',
    'Performance by Subject': 'Performance by Subject',
    'Learning Pattern Analysis': 'Learning Pattern Analysis',
    'AI-Powered Recommendations': 'AI-Powered Recommendations',
    'Learning Goals & Milestones': 'Learning Goals & Milestones',
    'Progress Overview': 'Progress Overview',
    'Skill Development': 'Skill Development',
    'Performance': 'Performance',
    'AI Insights': 'AI Insights',
    
    // Study Tools
    'Study Tools': 'Study Tools',
    'Organize your learning with notes, flashcards, and study planning': 'Organize your learning with notes, flashcards, and study planning',
    'Notes': 'Notes',
    'Flashcards': 'Flashcards',
    'Study Calendar': 'Study Calendar',
    'Overview': 'Overview',
    'My Notes': 'My Notes',
    'New Note': 'New Note',
    'Create New Note': 'Create New Note',
    'Create New Flashcard': 'Create New Flashcard',
    'Create Study Event': 'Create Study Event',
    'Upcoming Events': 'Upcoming Events',
    'Review Session': 'Review Session',
    'Quick Actions': 'Quick Actions',
    'Recent Activity': 'Recent Activity',
    
    // Forums
    'Discussion Forums': 'Discussion Forums',
    'Connect with peers, ask questions, and share knowledge': 'Connect with peers, ask questions, and share knowledge',
    'Discussions': 'Discussions',
    'Study Groups': 'Study Groups',
    'Q&A': 'Q&A',
    'New Discussion': 'New Discussion',
    'Create Group': 'Create Group',
    'Join Group': 'Join Group',
    'Post Discussion': 'Post Discussion',
    'Post Reply': 'Post Reply',
    'Accepted Answer': 'Accepted Answer',
    'reputation': 'reputation',
    
    // Certificates
    'Certificates & Credentials': 'Certificates & Credentials',
    'Your earned certificates, badges, and digital credentials': 'Your earned certificates, badges, and digital credentials',
    'Certificates': 'Certificates',
    'Badges': 'Badges',
    'Digital Credentials': 'Digital Credentials',
    'Share & Verify': 'Share & Verify',
    'Certificate of Completion': 'Certificate of Completion',
    'This is to certify that': 'This is to certify that',
    'has successfully completed the course': 'has successfully completed the course',
    'Completion Date': 'Completion Date',
    'Final Grade': 'Final Grade',
    'Credits Earned': 'Credits Earned',
    'Course Instructor': 'Course Instructor',
    'Digital Learning Platform': 'Digital Learning Platform',
    'Certificate No': 'Certificate No',
    'Blockchain Verified': 'Blockchain Verified',
    'Share Your Achievements': 'Share Your Achievements',
    'Verification Link': 'Verification Link',
    'cart.alreadyInCart': 'Course is already in your cart',
    'cart.cartCleared': 'Cart cleared',
    'cart.selectPaymentMethod': 'Please select a payment method',
    'cart.fillCardDetails': 'Please fill in all card details',
    'cart.enrollmentSuccess': 'Successfully enrolled in',
    'cart.paymentFailed': 'Payment failed. Please try again.',
    'cart.secureCheckout': 'Secure checkout powered by CogneraX',

    // Quiz Taking
    'quiz.loading': 'Loading quiz...',
    'quiz.timeLimit': 'Time Limit',
    'quiz.minutes': 'minutes',
    'quiz.questions': 'Questions',
    'quiz.totalPoints': 'Total Points',
    'quiz.instructions': 'This quiz will be taken in fullscreen mode. Switching tabs or windows will be tracked as suspicious activity.',
    'quiz.startQuiz': 'Start Quiz',
    'quiz.started': 'Quiz started! Good luck!',
    'quiz.timeUp': 'Time is up! Submitting quiz...',
    'quiz.submitted': 'Quiz submitted successfully!',
    'quiz.submitting': 'Submitting...',
    'quiz.submit': 'Submit Quiz',
    'quiz.submitError': 'Error submitting quiz. Please try again.',
    'quiz.previous': 'Previous',
    'quiz.next': 'Next',
    'quiz.question': 'Question',
    'quiz.points': 'points',
    'quiz.true': 'True',
    'quiz.false': 'False',
    'quiz.shortAnswerPlaceholder': 'Enter your answer...',
    'quiz.codeCompletionPlaceholder': 'Complete the code...',
    'quiz.questionOverview': 'Question Overview',
    'quiz.completed': 'Quiz Completed!',
    'quiz.results': 'Here are your results',
    'quiz.score': 'Score',
    'quiz.correctAnswers': 'Correct Answers',
    'quiz.suspiciousActivityDetected': 'Suspicious activity detected',
    'quiz.incidents': 'incidents',
    'quiz.notFocused': 'Not Focused',
    'quiz.suspicious.tabSwitch': 'Tab switched',
    'quiz.suspicious.windowBlur': 'Window lost focus',
    'quiz.suspicious.fullscreenExit': 'Exited fullscreen',
    'quiz.suspicious.rightClick': 'Right-click detected',
    'quiz.suspicious.devTools': 'Developer tools attempt',
    'quiz.warning.tabSwitch': 'Warning: Tab switching detected!',
    'quiz.warning.fullscreen': 'Warning: Please stay in fullscreen mode!',
    'quiz.warning.devTools': 'Warning: Developer tools not allowed!',
    'common.backToDashboard': 'Back to Dashboard',
    
    // Admin
    'admin.platformAnalytics': 'Platform Analytics',
    'admin.platformAnalyticsDesc': 'Comprehensive insights into platform performance and user engagement',
    'admin.userAccessManagement': 'User & Access Management',
    'admin.userAccessDesc': 'Manage users, roles, permissions, and access controls',
    'admin.systemAdministration': 'System Administration',
    'admin.systemAdminDesc': 'Monitor system health, audit logs, and manage backups',
    'admin.platformConfiguration': 'Platform Configuration',
    'admin.platformConfigDesc': 'Customize platform appearance, features, and integrations',

    // AI Enhancements
    'ai.intelligentTutoring': 'Intelligent Tutoring System',
    'ai.intelligentTutoringDesc': 'Get personalized hints, guidance, and AI-powered learning assistance',
    'ai.essayGrading': 'AI Essay Grading & Feedback',
    'ai.essayGradingDesc': 'Automated essay evaluation with detailed feedback and improvement suggestions',
    'ai.recommendationEngine': 'AI Content Recommendation Engine',
    'ai.recommendationDesc': 'Personalized learning recommendations powered by AI and your learning patterns',
    'ai.sessionsToday': 'Sessions Today',
    'ai.hintsProvided': 'Hints Provided',
    'ai.conceptsMastered': 'Concepts Mastered',
    'ai.learningStreak': 'Learning Streak',
    'ai.aiChat': 'AI Chat',
    'ai.personalizedHints': 'Personalized Hints',
    'ai.learningPath': 'Learning Path',
    'ai.intelligentTutor': 'Intelligent Tutor',
    'ai.currentTopic': 'Current Topic',
    'ai.askQuestion': 'Ask a question or describe what you\'re struggling with...',
    'ai.learningContext': 'Learning Context',
    'ai.currentCourse': 'Current Course',
    'ai.currentLesson': 'Current Lesson',
    'ai.learningStyle': 'Learning Style',
    'ai.strugglingAreas': 'Struggling Areas',
    'ai.strengths': 'Strengths',
    'ai.examples': 'Examples',
    'ai.practiceThis': 'Practice This Concept',
    'ai.adaptiveLearningPath': 'Adaptive Learning Path',
    'ai.learningPathDesc': 'Your personalized journey based on performance and learning style',
    'ai.overallProgress': 'Overall Progress',
    'ai.completed': 'Completed',
    'ai.inProgress': 'In Progress',
    'ai.upcoming': 'Upcoming',
    'ai.aiRecommendations': 'AI Recommendations',
    'ai.averageSessionTime': 'Average Session Time',
    'ai.thisWeek': 'This week',
    'ai.totalQuestions': 'Total Questions Asked',
    'ai.allTime': 'All time',
    'ai.helpfulnessRating': 'Helpfulness Rating',
    'ai.basedOnFeedback': 'Based on your feedback',
    'ai.learningImpact': 'Learning Impact',
    'ai.learningImpactDesc': 'How AI tutoring has improved your understanding',
    'ai.conceptUnderstanding': 'Concept Understanding',
    'ai.problemSolvingSpeed': 'Problem Solving Speed',
    'ai.confidenceLevel': 'Confidence Level',
    'ai.essaysGradedToday': 'Essays Graded Today',
    'ai.averageGradingTime': 'Avg. Grading Time',
    'ai.averageScore': 'Average Score',
    'ai.thisMonth': 'This Month',
    'ai.essays': 'Essays',
    'ai.aiGrading': 'AI Grading',
    'ai.criteria': 'Criteria',
    'ai.submittedEssays': 'Submitted Essays',
    'ai.bulkGrade': 'Bulk Grade',
    'ai.uploadEssays': 'Upload Essays',
    'ai.gradingProgress': 'Grading Progress',
    'ai.overallScore': 'Overall Score',
    'ai.viewFeedback': 'View Feedback',
    'ai.gradeNow': 'Grade Now',
    'ai.scoreBreakdown': 'Score Breakdown',
    'ai.areasForImprovement': 'Areas for Improvement',
    'ai.aiSuggestions': 'AI Suggestions',
    'ai.overallGrade': 'Overall Grade',
    'ai.essayDetails': 'Essay Details',
    'ai.wordCount': 'Word Count',
    'ai.submitted': 'Submitted',
    'ai.gradingTime': 'Grading Time',
    'ai.selectEssayToView': 'Select an essay to view detailed feedback',
    'ai.selectEssayDesc': 'Choose a graded essay from the essays tab to see AI-generated feedback and suggestions',
    'ai.noEssaySelected': 'No essay selected',
    'ai.commonIssues': 'Most Common Issues',
    'ai.improvementTrends': 'Improvement Trends',
    'ai.gradingAccuracy': 'AI Grading Accuracy',
    'ai.gradingAccuracyDesc': 'Comparison with human graders and validation metrics',
    'ai.overallAccuracy': 'Overall Accuracy',
    'ai.consistencyRate': 'Consistency Rate',
    'ai.averageProcessingTime': 'Avg. Processing Time',
    'ai.gradingCriteria': 'Grading Criteria',
    'ai.gradingCriteriaDesc': 'Configure how essays are evaluated and scored',
    'ai.selectCriteria': 'Select Grading Criteria',
    'ai.currentSettings': 'Current Settings',
    'ai.structureWeight': 'Structure Weight',
    'ai.contentWeight': 'Content Weight',
    'ai.grammarWeight': 'Grammar Weight',
    'ai.originalityWeight': 'Originality Weight',
    'ai.feedbackSettings': 'Feedback Settings',
    'ai.detailedFeedback': 'Detailed Feedback',
    'ai.enabled': 'Enabled',
    'ai.improvementSuggestions': 'Improvement Suggestions',
    'ai.exampleProvision': 'Example Provision',
    'ai.plagiarismCheck': 'Plagiarism Check',
    'ai.exportFeedback': 'Export Feedback',
    'ai.sendToStudent': 'Send to Student',
    'ai.totalRecommendations': 'Total Recommendations',
    'ai.acceptanceRate': 'Acceptance Rate',
    'ai.matchScore': 'Avg. Match Score',
    'ai.timesSaved': 'Hours Saved',
    'ai.recommendations': 'Recommendations',
    'ai.learningProfile': 'Learning Profile',
    'ai.searchRecommendations': 'Search recommendations...',
    'ai.allCategories': 'All Categories',
    'ai.dataScience': 'Data Science',
    'ai.mathematics': 'Mathematics',
    'ai.careerDevelopment': 'Career Development',
    'ai.mentorship': 'Mentorship',
    'ai.events': 'Events',
    'ai.generateNew': 'Generate New',
    'ai.whyRecommended': 'Why recommended:',
    'ai.viewDetails': 'View Details',
    'ai.personalizedLearningPath': 'Personalized Learning Path',
    'ai.learningPreferences': 'Learning Preferences',
    'ai.preferredStyle': 'Preferred Learning Style',
    'ai.interests': 'Interests',
    'ai.goals': 'Learning Goals',
    'ai.learningStats': 'Learning Statistics',
    'ai.completedCourses': 'Completed Courses',
    'ai.averageRating': 'Average Rating',
    'ai.preferredDifficulty': 'Preferred Difficulty',
    'ai.studyTime': 'Preferred Study Time',
    'ai.aiInsights': 'AI Insights',
    'ai.aiInsightsDesc': 'How AI understands your learning patterns and preferences',
    'ai.learningPattern': 'Learning Pattern Analysis',
    'ai.learningPatternDesc': 'You prefer visual and interactive learning experiences with moderate difficulty progression. Your engagement is highest during evening study sessions, and you show strong completion rates for project-based content.',
    'ai.skillGaps': 'Identified Skill Gaps',
    'ai.skillGapsDesc': 'Based on your course history and career goals, we\'ve identified opportunities to strengthen your foundation in advanced statistics and deep learning frameworks.',
    'ai.nextSteps': 'Recommended Next Steps',
    'ai.nextStepsDesc': 'Focus on practical applications of machine learning through project-based courses. Consider joining study groups for peer learning opportunities.',
    'ai.recommendationAccuracy': 'Recommendation Accuracy',
    'ai.last30Days': 'Last 30 days',
    'ai.engagementRate': 'Engagement Rate',
    'ai.recommendedContent': 'With recommended content',
    'ai.timeSaved': 'Time Saved',
    'ai.throughSmartRecommendations': 'Through smart recommendations',
    'ai.recommendationTrends': 'Recommendation Trends',
    'ai.recommendationTrendsDesc': 'How your recommendation preferences have evolved over time',
    'ai.technicalContent': 'Technical Content',
    'ai.practicalProjects': 'Practical Projects',
    'ai.theoryBasedLearning': 'Theory-based Learning',
    'ai.collaborativeLearning': 'Collaborative Learning',
    'ai.type': 'Type',
    'ai.duration': 'Duration',
    'ai.difficulty': 'Difficulty',
    'ai.prerequisites': 'Prerequisites',
    'ai.startLearning': 'Start Learning',
    'ai.successRate': 'Success Rate',

    // AI Credits Management
    'aiCredits.title': 'AI Credits Management',
    'aiCredits.description': 'Manage AI credits distribution and track usage across your organization',
    'aiCredits.totalCredits': 'Total Credits',
    'aiCredits.used': 'Used Credits',
    'aiCredits.remaining': 'Remaining Credits',
    'aiCredits.monthlyUsage': 'Monthly Usage',
    'aiCredits.instructors': 'Instructors',
    'aiCredits.usage': 'Usage History',
    'aiCredits.analytics': 'Analytics',
    'aiCredits.settings': 'Settings',
    'aiCredits.searchInstructors': 'Search instructors...',
    'aiCredits.allRoles': 'All Roles',
    'aiCredits.bulkAllocate': 'Bulk Allocate',
    'aiCredits.allocated': 'Allocated',
    'aiCredits.usageBreakdown': 'Usage Breakdown',
    'aiCredits.contentAnalysis': 'Content Analysis',
    'aiCredits.quizGeneration': 'Quiz Generation',
    'aiCredits.essayGrading': 'Essay Grading',
    'aiCredits.tutoring': 'AI Tutoring',
    'aiCredits.lastActive': 'Last active',
    'aiCredits.recentActivity': 'Recent Activity',
    'aiCredits.recentActivityDesc': 'Track all credit-related activities in your organization',
    'aiCredits.averageUsage': 'Average Monthly Usage',
    'aiCredits.creditsPerMonth': 'credits per month',
    'aiCredits.mostUsedFeature': 'Most Used Feature',
    'aiCredits.ofTotalUsage': 'of total usage',
    'aiCredits.topUser': 'Top User This Month',
    'aiCredits.creditsUsed': 'credits used',
    'aiCredits.usageTrends': 'Usage Trends',
    'aiCredits.usageTrendsDesc': 'AI credits usage patterns across different features',
    'aiCredits.creditSettings': 'Credit Settings',
    'aiCredits.creditSettingsDesc': 'Configure credit allocation and usage policies',
    'aiCredits.allocationRules': 'Allocation Rules',
    'aiCredits.autoAllocate': 'Auto-allocate monthly',
    'aiCredits.enabled': 'Enabled',
    'aiCredits.rolloverUnused': 'Rollover unused credits',
    'aiCredits.alertLowBalance': 'Alert on low balance',
    'aiCredits.usageLimits': 'Usage Limits',
    'aiCredits.dailyLimit': 'Daily limit per instructor',
    'aiCredits.credits': 'credits',
    'aiCredits.monthlyLimit': 'Monthly limit per instructor',
    'aiCredits.minAllocation': 'Minimum allocation',
    'aiCredits.creditCosts': 'Credit Costs per Feature',
    'aiCredits.allocateCredits': 'Allocate Credits',
    'aiCredits.allocatingTo': 'Allocating credits to',
    'aiCredits.enterAmount': 'Enter credit amount',
    'aiCredits.allocate': 'Allocate',
    'aiCredits.bulkAllocateDesc': 'Credits will be distributed equally among all instructors',
    'aiCredits.totalCredits': 'Total credits to distribute',
    'aiCredits.creditsPerInstructor': 'credits per instructor',
    'aiCredits.distribute': 'Distribute',
    'aiCredits.credit': 'credit',
  },
  ar: {
    // Authentication
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.logout': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.fullName': 'الاسم الكامل',
    'auth.organization': 'المؤسسة',
    'auth.welcomeBack': 'مرحباً بعودتك',
    'auth.createAccount': 'إنشاء حساب',
    'auth.signInToAccount': 'تسجيل الدخول إلى حسابك',
    'auth.dontHaveAccount': 'ليس لديك حساب؟',
    'auth.alreadyHaveAccount': 'لديك حساب بالفعل؟',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.rememberMe': 'تذكرني',
    
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.courses': 'الدورات',
    'nav.students': 'الطلاب',
    'nav.analytics': 'التحليلات',
    'nav.settings': 'الإعدادات',
    'nav.profile': 'الملف الشخصي',
    'nav.organization': 'المؤسسة',
    'nav.contentAnalysis': 'تحليل المحتوى',
    'nav.quizCreator': 'منشئ الاختبارات',
    'nav.questionBank': 'بنك الأسئلة',
    'nav.courseManagement': 'إدارة الدورات',
    'nav.myCourses': 'دوراتي',
    'nav.courseDiscovery': 'استكشاف الدورات',
    'nav.submissions': 'التسليمات والواجبات',
    'nav.quizResults': 'نتائج الاختبارات',
    'nav.achievements': 'الإنجازات',
    'nav.cart': 'عربة التسوق',
    'nav.takeQuiz': 'اجراء الاختبار',
    'nav.analytics': 'تحليلات التعلم',
    'nav.studyTools': 'أدوات الدراسة',
    'nav.forums': 'منتديات النقاش',
    'nav.certificates': 'الشهادات',
    'nav.instructorAnalytics': 'التحليلات المتقدمة',
    'nav.gradebook': 'سجل الدرجات والتقييم',
    'nav.communicationHub': 'مركز الاتصالات',
    'nav.contentAuthoring': 'إنشاء المحتوى',
    'nav.platformAnalytics': 'تحليلات المنصة',
    'nav.userAccessManagement': 'إدارة المستخدمين والوصول',
    'nav.systemAdministration': 'إدارة النظام',
    'nav.platformConfiguration': 'إعداد المنصة',
    'nav.aiTutoring': 'نظام التدريس الذكي',
    'nav.aiEssayGrading': 'تقييم المقالات بالذكاء الاصطناعي',
    'nav.aiRecommendations': 'توصيات الذكاء الاصطناعي',
    'nav.aiCredits': 'إدارة رصيد الذكاء الاصطناعي',
    
    // Common
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.view': 'عرض',
    'common.add': 'إضافة',
    'common.remove': 'إزالة',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.loading': 'جارٍ التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.warning': 'تحذير',
    'common.info': 'معلومات',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.submit': 'إرسال',
    'common.reset': 'إعادة تعيين',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.by': 'بواسطة',
    'common.previous': 'السابق',
    'common.close': 'إغلاق',
    'common.open': 'فتح',
    'common.language': 'اللغة',
    
    // Dashboard
    'dashboard.welcome': 'مرحباً بك في CogneraX Learn',
    'dashboard.totalStudents': 'إجمالي الطلاب',
    'dashboard.activeCourses': 'الدورات النشطة',
    'dashboard.completionRate': 'معدل الإكمال',
    'dashboard.aiCredits': 'رصيد الذكاء الاصطناعي',
    'dashboard.recentActivity': 'النشاط الأخير',
    'dashboard.overview': 'نظرة عامة',
    'dashboard.analytics': 'التحليلات',
    
    // Courses
    'courses.createCourse': 'إنشاء دورة',
    'courses.manageCourses': 'إدارة الدورات',
    'courses.enrolledCourses': 'الدورات المسجلة',
    'courses.availableCourses': 'الدورات المتاحة',
    'courses.courseName': 'اسم الدورة',
    'courses.courseDescription': 'وصف الدورة',
    'courses.instructor': 'المدرب',
    'courses.duration': 'المدة',
    'courses.difficulty': 'مستوى الصع��بة',
    'courses.enrolled': 'مسجل',
    'courses.completed': 'مكتمل',
    'courses.inProgress': 'قيد التقدم',
    'courses.notStarted': 'لم يبدأ',
    
    // Achievements
    'achievements.title': 'الإنجازات',
    'achievements.description': 'تتبع معالم التعلم الخاصة بك واحصل على الإنجازات أثناء تقدمك في رحلتك التعليمية.',
    'achievements.totalPoints': 'إجمالي النقاط',
    'achievements.earned': 'محققة',
    'achievements.pending': 'معلقة',
    'achievements.completion': 'الإنجاز',
    'achievements.allAchievements': 'جميع الإنجازات',
    'achievements.earnedAchievements': 'الإنجازات المحققة',
    'achievements.pendingAchievements': 'الإنجازات المعلقة',
    'achievements.progress': 'التقدم',
    'achievements.requirements': 'المتطلبات',
    'achievements.earnedOn': 'تم تحقيقه في',
    'achievements.points': 'نقطة',
    'achievements.leaderboard': 'لوحة الصدارة للإنجازات',
    'achievements.viewLeaderboard': 'عرض لوحة الصدارة الكاملة',
    'achievements.rank': 'المرتبة',
    
    // AI Credits
    'aiCredits.title': 'رصيد الذكاء الاصطناعي',
    'aiCredits.available': 'الرصيد المتاح',
    'aiCredits.used': 'الرصيد المستخدم',
    'aiCredits.remaining': 'الرصيد المتبقي',
    'aiCredits.distribute': 'توزيع الرصيد',
    'aiCredits.usage': 'الاستخدام',
    
    // Settings
    'settings.general': 'الإعدادات العامة',
    'settings.profile': 'إعدادات الملف الشخصي',
    'settings.security': 'إعدادات الأمان',
    'settings.notifications': 'إعدادات الإشعارات',
    'settings.language': 'إعدادات اللغة',
    'settings.theme': 'إعدادات المظهر',
    
    // Errors and Messages
    'error.somethingWentWrong': 'حدث خطأ ما',
    'error.networkError': 'حدث خطأ في الشبكة',
    'error.invalidCredentials': 'بيانات اعتماد غير صحيحة',
    'success.loginSuccess': 'تم تسجيل الدخول بنجاح',
    'success.signupSuccess': 'تم إنشاء الحساب بنجاح',
    'success.saveSuccess': 'تم حفظ التغييرات بنجاح',
    'success.deleteSuccess': 'تم حذف العنصر بنجاح',
    
    // Time and Dates
    'time.today': 'اليوم',
    'time.yesterday': 'أمس',
    'time.thisWeek': 'هذا الأسبوع',
    'time.thisMonth': 'هذا الشهر',
    'time.minute': 'دقيقة',
    'time.minutes': 'دقائق',
    'time.hour': 'ساعة',
    'time.hours': 'ساعات',
    'time.day': 'يوم',
    'time.days': 'أيام',
    'time.week': 'أسبوع',
    'time.weeks': 'أسابيع',
    'time.month': 'شهر',
    'time.months': 'أشهر',
    'time.year': 'سنة',
    'time.years': 'سنوات',
    
    // Cart
    'cart.title': 'عربة التسوق',
    'cart.subtitle': 'راجع واشترِ الدورات التي اخترتها',
    'cart.emptyTitle': 'عربة التسوق فارغة',
    'cart.emptyDescription': 'تصفح كتالوج الدورات وأضف الدورات إلى عربة التسوق للبدء.',
    'cart.browseCourses': 'تصفح الدورات',
    'cart.clearCart': 'إفراغ عربة التسوق',
    'cart.orderSummary': 'ملخص الطلب',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.tax': 'الضريبة',
    'cart.total': 'المجموع الكلي',
    'cart.proceedToCheckout': 'المتابعة للدفع',
    'cart.checkout': 'الدفع',
    'cart.addedToCart': 'تمت إضافة الدورة إلى عربة التسوق',
    'cart.removedFromCart': 'تمت إزالة الدورة من عربة التسوق',
    'cart.alreadyInCart': 'الدورة موجودة بالفعل في عربة التسوق',
    'cart.cartCleared': 'تم إفراغ عربة التسوق',
    'cart.selectPaymentMethod': 'يرجى اختيار طريقة الدفع',
    'cart.fillCardDetails': 'يرجى ملء جميع تفاصيل البطاقة',
    'cart.enrollmentSuccess': 'تم التسجيل بنجاح في',
    'cart.paymentFailed': 'فشل في الدفع. يرجى المحاولة مرة أخرى.',
    'cart.secureCheckout': 'دفع آمن مدعوم من CogneraX',

    // Quiz Taking
    'quiz.loading': 'جارٍ تحميل الاختبار...',
    'quiz.timeLimit': 'حد الوقت',
    'quiz.minutes': 'دقائق',
    'quiz.questions': 'الأسئلة',
    'quiz.totalPoints': 'إجمالي النقاط',
    'quiz.instructions': 'سيتم إجراء هذا الاختبار في وضع ملء الشاشة. سيتم تتبع تبديل علامات التبويب أو النوافذ كنشاط مشبوه.',
    'quiz.startQuiz': 'بدء الاختبار',
    'quiz.started': 'بدأ الاختبار! حظاً موفقاً!',
    'quiz.timeUp': 'انتهى الوقت! جارٍ إرسال الاختبار...',
    'quiz.submitted': 'تم إرسال الاختبار بنجاح!',
    'quiz.submitting': 'جارٍ الإرسال...',
    'quiz.submit': 'إرسال الاختبار',
    'quiz.submitError': 'خطأ في إرسال الاختبار. يرجى المحاولة مرة أخرى.',
    'quiz.previous': 'السابق',
    'quiz.next': 'التالي',
    'quiz.question': 'السؤال',
    'quiz.points': 'نقاط',
    'quiz.true': 'صحيح',
    'quiz.false': 'خطأ',
    'quiz.shortAnswerPlaceholder': 'أدخل إجابتك...',
    'quiz.codeCompletionPlaceholder': 'أكمل الكود...',
    'quiz.questionOverview': 'نظرة عامة على الأسئلة',
    'quiz.completed': 'اكتمل الاختبار!',
    'quiz.results': 'إليك نتائجك',
    'quiz.score': 'النتيجة',
    'quiz.correctAnswers': 'الإجابات الصحيحة',
    'quiz.suspiciousActivityDetected': 'تم اكتشاف نشاط مشبوه',
    'quiz.incidents': 'حوادث',
    'quiz.notFocused': 'غير مركز',
    'quiz.suspicious.tabSwitch': 'تم تبديل علامة التبويب',
    'quiz.suspicious.windowBlur': 'فقدت النافذة التركيز',
    'quiz.suspicious.fullscreenExit': 'خرج من وضع ملء الشاشة',
    'quiz.suspicious.rightClick': 'تم اكتشاف النقر بالزر الأيمن',
    'quiz.suspicious.devTools': 'محاولة فتح أدوات المطور',
    'quiz.warning.tabSwitch': 'تحذير: تم اكتشاف تبديل علامة التبويب!',
    'quiz.warning.fullscreen': 'تحذير: يرجى البقاء في وضع ملء الشاشة!',
    'quiz.warning.devTools': 'تحذير: أدوات المطور غير مسموحة!',
    'common.backToDashboard': 'العودة إلى لوحة التحكم',
    
    // Admin
    'admin.platformAnalytics': 'تحليلات المنصة',
    'admin.platformAnalyticsDesc': 'رؤى شاملة حول أداء المنصة ومشاركة المستخدمين',
    'admin.userAccessManagement': 'إدارة المستخدمين والوصول',
    'admin.userAccessDesc': 'إدارة المستخدمين والأدوار والصلاحيات وضوابط الوصول',
    'admin.systemAdministration': 'إدارة النظام',
    'admin.systemAdminDesc': 'مراقبة صحة النظام وسجلات التدقيق وإدارة النسخ الاحتياطية',
    'admin.platformConfiguration': 'إعداد المنصة',
    'admin.platformConfigDesc': 'تخصيص مظهر المنصة والميزات والتكاملات',

    // AI Enhancements Arabic
    'ai.intelligentTutoring': 'نظام التدريس الذكي',
    'ai.intelligentTutoringDesc': 'احصل على إرشادات وتلميحات شخصية ومساعدة تعليمية مدعومة بالذكاء الاصطناعي',
    'ai.essayGrading': 'تقييم المقالات والملاحظات بالذكاء الاصطناعي',
    'ai.essayGradingDesc': 'تقييم آلي للمقالات مع ملاحظات مفصلة واقتراحات للتحسين',
    'ai.recommendationEngine': 'محرك توصيات المحتوى بالذكاء الاصطناعي',
    'ai.recommendationDesc': 'توصيات تعليمية شخصية مدعومة بالذكاء الاصطناعي وأنماط التعلم الخاصة بك',
    'ai.sessionsToday': 'الجلسات اليوم',
    'ai.hintsProvided': 'التلميحات المقدمة',
    'ai.conceptsMastered': 'المفاهيم المتقنة',
    'ai.learningStreak': 'شريط التعلم',
    'ai.aiChat': 'محادثة الذكاء الاصطناعي',
    'ai.personalizedHints': 'تلميحات شخصية',
    'ai.learningPath': 'مسار التعلم',
    'ai.intelligentTutor': 'المدرس الذكي',
    'ai.currentTopic': 'الموضوع الحالي',
    'ai.askQuestion': 'اطرح سؤالاً أو اوصف ما تواجه صعوبة فيه...',
    'ai.learningContext': 'سياق التعلم',
    'ai.currentCourse': 'الدورة الحالية',
    'ai.currentLesson': 'الدرس الحالي',
    'ai.learningStyle': 'أسلوب التعلم',
    'ai.strugglingAreas': 'المناطق الصعبة',
    'ai.strengths': 'نقاط القوة',
    'ai.examples': 'أمثلة',
    'ai.practiceThis': 'تدرب على هذا المفهوم',
    'ai.adaptiveLearningPath': 'مسار التعلم التكيفي',
    'ai.learningPathDesc': 'رحلتك الشخصية المبنية على الأداء وأسلوب التعلم',
    'ai.overallProgress': 'التقدم العام',
    'ai.completed': 'مكتمل',
    'ai.inProgress': 'قيد التقدم',
    'ai.upcoming': 'قادم',
    'ai.aiRecommendations': 'توصيات الذكاء الاصطناعي',
    'ai.averageSessionTime': 'متوسط وقت الجلسة',
    'ai.thisWeek': 'هذا الأسبوع',
    'ai.totalQuestions': 'إجمالي الأسئلة المطروحة',
    'ai.allTime': 'كل الوقت',
    'ai.helpfulnessRating': 'تقييم المساعدة',
    'ai.basedOnFeedback': 'بناءً على ملاحظاتك',
    'ai.learningImpact': 'تأثير التعلم',
    'ai.learningImpactDesc': 'كيف حسن التدريس بالذكاء الاصطناعي من فهمك',
    'ai.conceptUnderstanding': 'فهم المفاهيم',
    'ai.problemSolvingSpeed': 'سرعة حل المشكلات',
    'ai.confidenceLevel': 'مستوى الثقة',
    'ai.essaysGradedToday': 'المقالات المقيمة اليوم',
    'ai.averageGradingTime': 'متوسط وقت التقييم',
    'ai.averageScore': 'متوسط النتيجة',
    'ai.thisMonth': 'هذا الشهر',
    'ai.essays': 'المقالات',
    'ai.aiGrading': 'التقييم بالذكاء الاصطناعي',
    'ai.criteria': 'المعايير',
    'ai.submittedEssays': 'المقالات المرسلة',
    'ai.bulkGrade': 'تقييم جماعي',
    'ai.uploadEssays': 'رفع المقالات',
    'ai.gradingProgress': 'تقدم التقييم',
    'ai.overallScore': 'النتيجة الإجمالية',
    'ai.viewFeedback': 'عرض الملاحظات',
    'ai.gradeNow': 'قيم الآن',
    'ai.scoreBreakdown': 'تفصيل النتائج',
    'ai.areasForImprovement': 'مناطق للتحسين',
    'ai.aiSuggestions': 'اقتراحات الذكاء الاصطناعي',
    'ai.overallGrade': 'الدرجة الإجمالية',
    'ai.essayDetails': 'تفاصيل المقال',
    'ai.wordCount': 'عدد الكلمات',
    'ai.submitted': 'مرسل',
    'ai.gradingTime': 'وقت التقييم',
    'ai.selectEssayToView': 'اختر مقالاً لعرض الملاحظات التفصيلية',
    'ai.selectEssayDesc': 'اختر مقالاً مقيماً من تبويب المقالات لرؤية ملاحظات الذكاء الاصطناعي والاقتراحات',
    'ai.noEssaySelected': 'لم يتم اختيار مقال',
    'ai.commonIssues': 'المشاكل الأكثر شيوعاً',
    'ai.improvementTrends': 'اتجاهات التحسين',
    'ai.gradingAccuracy': 'دقة التقييم بالذكاء الاصطناعي',
    'ai.gradingAccuracyDesc': 'مقارنة مع المقيمين البشر ومقاييس التحقق',
    'ai.overallAccuracy': 'الدقة الإجمالية',
    'ai.consistencyRate': 'معدل الاتساق',
    'ai.averageProcessingTime': 'متوسط وقت المعالجة',
    'ai.gradingCriteria': 'معايير التقييم',
    'ai.gradingCriteriaDesc': 'تكوين كيفية تقييم وتسجيل المقالات',
    'ai.selectCriteria': 'اختر معايير التقييم',
    'ai.currentSettings': 'الإعدادات الحالية',
    'ai.structureWeight': 'وزن البنية',
    'ai.contentWeight': 'وزن المحتوى',
    'ai.grammarWeight': 'وزن القواعد',
    'ai.originalityWeight': 'وزن الأصالة',
    'ai.feedbackSettings': 'إعدادات الملاحظات',
    'ai.detailedFeedback': 'ملاحظات مفصلة',
    'ai.enabled': 'مفعل',
    'ai.improvementSuggestions': 'اقتراحات التحسين',
    'ai.exampleProvision': 'توفير الأمثلة',
    'ai.plagiarismCheck': 'فحص الانتحال',
    'ai.exportFeedback': 'تصدير الملاحظات',
    'ai.sendToStudent': 'إرسال للطالب',
    'ai.totalRecommendations': 'إجمالي التوصيات',
    'ai.acceptanceRate': 'معدل القبول',
    'ai.matchScore': 'متوسط نقاط التطابق',
    'ai.timesSaved': 'الساعات الموفرة',
    'ai.recommendations': 'التوصيات',
    'ai.learningProfile': 'ملف التعلم',
    'ai.searchRecommendations': 'البحث في التوصيات...',
    'ai.allCategories': 'جميع الفئات',
    'ai.dataScience': 'علم البيانات',
    'ai.mathematics': 'الرياضيات',
    'ai.careerDevelopment': 'التطوير المهني',
    'ai.mentorship': 'الإرشاد',
    'ai.events': 'الأحداث',
    'ai.generateNew': 'إنشاء جديد',
    'ai.whyRecommended': 'لماذا موصى به:',
    'ai.viewDetails': 'عرض التفاصيل',
    'ai.personalizedLearningPath': 'مسار التعلم الشخصي',
    'ai.learningPreferences': 'تفضيلات التعلم',
    'ai.preferredStyle': 'أسلوب التعلم المفضل',
    'ai.interests': 'الاهتمامات',
    'ai.goals': 'أهداف التعلم',
    'ai.learningStats': 'إحصائيات التعلم',
    'ai.completedCourses': 'الدورات المكتملة',
    'ai.averageRating': 'متوسط التقييم',
    'ai.preferredDifficulty': 'مستوى الصعوبة المفضل',
    'ai.studyTime': 'وقت الدراسة المفضل',
    'ai.aiInsights': 'رؤى الذكاء الاصطناعي',
    'ai.aiInsightsDesc': 'كيف يفهم الذكاء الاصطناعي أنماط وتفضيلات التعلم الخاصة بك',
    'ai.learningPattern': 'تحليل نمط التعلم',
    'ai.learningPatternDesc': 'تفضل تجارب التعلم البصرية والتفاعلية مع تقدم متوسط الصعوبة. مشاركتك أعلى خلال جلسات الدراسة المسائية، وتظهر معدلات إكمال قوية للمحتوى القائم على المشاريع.',
    'ai.skillGaps': 'فجوات المهارات المحددة',
    'ai.skillGapsDesc': 'بناءً على تاريخ دوراتك وأهدافك المهنية، حددنا فرصاً لتقوية أساسك في الإحصاء المتقدم وأطر التعلم العميق.',
    'ai.nextSteps': 'الخطوات التالية الموصى بها',
    'ai.nextStepsDesc': 'ركز على التطبيقات العملية للتعلم الآلي من خلال الدورات القائمة على المشاريع. فكر في الانضمام إلى مجموعات الدراسة لفرص التعلم من الأقران.',
    'ai.recommendationAccuracy': 'دقة التوصية',
    'ai.last30Days': 'آخر 30 يوماً',
    'ai.engagementRate': 'معدل المشاركة',
    'ai.recommendedContent': 'مع المحتوى الموصى به',
    'ai.timeSaved': 'الوقت الموفر',
    'ai.throughSmartRecommendations': 'من خلال التوصيات الذكية',
    'ai.recommendationTrends': 'اتجاهات التوصيات',
    'ai.recommendationTrendsDesc': 'كيف تطورت تفضيلات التوصية الخاصة بك بمرور الوقت',
    'ai.technicalContent': 'المحتوى التقني',
    'ai.practicalProjects': 'المشاريع العملية',
    'ai.theoryBasedLearning': 'التعلم القائم على النظرية',
    'ai.collaborativeLearning': 'التعلم التعاوني',
    'ai.type': 'النوع',
    'ai.duration': 'المدة',
    'ai.difficulty': 'الصعوبة',
    'ai.prerequisites': 'المتطلبات المسبقة',
    'ai.startLearning': 'بدء التعلم',
    'ai.successRate': 'معدل النجاح',

    // AI Credits Management Arabic
    'aiCredits.title': 'إدارة رصيد الذكاء الاصطناعي',
    'aiCredits.description': 'إدارة توزيع رصيد الذكاء الاصطناعي وتتبع الاستخدام عبر مؤسستك',
    'aiCredits.totalCredits': 'إجمالي الرصيد',
    'aiCredits.used': 'الرصيد المستخدم',
    'aiCredits.remaining': 'الرصيد المتبقي',
    'aiCredits.monthlyUsage': 'الاستخدام الشهري',
    'aiCredits.instructors': 'المدرسون',
    'aiCredits.usage': 'تاريخ الاستخدام',
    'aiCredits.analytics': 'التحليلات',
    'aiCredits.settings': 'الإعدادات',
    'aiCredits.searchInstructors': 'البحث عن المدرسين...',
    'aiCredits.allRoles': 'جميع الأدوار',
    'aiCredits.bulkAllocate': 'التوزيع الجماعي',
    'aiCredits.allocated': 'المخصص',
    'aiCredits.usageBreakdown': 'تفصيل الاستخدام',
    'aiCredits.contentAnalysis': 'تحليل المحتوى',
    'aiCredits.quizGeneration': 'إنشاء الاختبارات',
    'aiCredits.essayGrading': 'تقييم المقالات',
    'aiCredits.tutoring': 'التدريس بالذكاء الاصطناعي',
    'aiCredits.lastActive': 'آخر نشاط',
    'aiCredits.recentActivity': 'النشاط الأخير',
    'aiCredits.recentActivityDesc': 'تتبع جميع الأنشطة المتعلقة بالرصيد في مؤسستك',
    'aiCredits.averageUsage': 'متوسط الاستخدام الشهري',
    'aiCredits.creditsPerMonth': 'رصيد شهرياً',
    'aiCredits.mostUsedFeature': 'الميزة الأكثر استخداماً',
    'aiCredits.ofTotalUsage': 'من إجمالي الاستخدام',
    'aiCredits.topUser': 'أكثر المستخدمين هذا الشهر',
    'aiCredits.creditsUsed': 'رصيد مستخدم',
    'aiCredits.usageTrends': 'اتجاهات الاستخدام',
    'aiCredits.usageTrendsDesc': 'أنماط استخدام رصيد الذكاء الاصطناعي عبر الميزات المختلفة',
    'aiCredits.creditSettings': 'إعدادات الرصيد',
    'aiCredits.creditSettingsDesc': 'تكوين تخصيص الرصيد وسياسات الاستخدام',
    'aiCredits.allocationRules': 'قواعد التخصيص',
    'aiCredits.autoAllocate': 'التخصيص التلقائي الشهري',
    'aiCredits.enabled': 'مفعل',
    'aiCredits.rolloverUnused': 'ترحيل الرصيد غير المستخدم',
    'aiCredits.alertLowBalance': 'تنبيه عند انخفاض الرصيد',
    'aiCredits.usageLimits': 'حدود الاستخدام',
    'aiCredits.dailyLimit': 'الحد اليومي لكل مدرس',
    'aiCredits.credits': 'رصيد',
    'aiCredits.monthlyLimit': 'الحد الشهري لكل مدرس',
    'aiCredits.minAllocation': 'الحد الأدنى للتخصيص',
    'aiCredits.creditCosts': 'تكلفة الرصيد لكل ميزة',
    'aiCredits.allocateCredits': 'تخصيص الرصيد',
    'aiCredits.allocatingTo': 'تخصيص الرصيد لـ',
    'aiCredits.enterAmount': 'أدخل مقدار الرصيد',
    'aiCredits.allocate': 'تخصيص',
    'aiCredits.bulkAllocateDesc': 'سيتم توزيع الرصيد بالتساوي بين جميع المدرسين',
    'aiCredits.totalCredits': 'إجمالي الرصيد للتوزيع',
    'aiCredits.creditsPerInstructor': 'رصيد لكل مدرس',
    'aiCredits.distribute': 'توزيع',
    'aiCredits.credit': 'رصيد',
  },
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Get saved language from localStorage or default to 'en'
    const saved = localStorage.getItem('cognerax-language');
    return (saved as Language) || 'en';
  });

  const isRTL = language === 'ar';

  // Save language preference and update document direction
  useEffect(() => {
    localStorage.setItem('cognerax-language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    
    // Update the document class for CSS targeting
    if (isRTL) {
      document.documentElement.classList.add('rtl');
      document.documentElement.classList.remove('ltr');
    } else {
      document.documentElement.classList.add('ltr');
      document.documentElement.classList.remove('rtl');
    }
  }, [language, isRTL]);

  // Translation function
  const t = (key: string, fallback?: string): string => {
    const translation = translations[language]?.[key];
    if (translation) return translation;
    
    // Fallback to English if Arabic translation is missing
    if (language === 'ar' && translations.en[key]) {
      return translations.en[key];
    }
    
    // Return fallback or key if no translation found
    return fallback || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
    isRTL,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};