// Parent Portal TypeScript Interfaces

export type UserRole = 'student' | 'instructor' | 'admin' | 'parent';

// Subscription for parent accounts
export interface Subscription {
  plan: 'standard';
  status: 'active' | 'inactive' | 'cancelled';
  childrenCount: number;
  amount: number;
  currency: string;
  startDate: string;
  renewalDate: string;
  paymentMethod?: string;
}

// Child invite generated by parent
export interface ChildInvite {
  token: string;
  email?: string;
  status: 'pending' | 'accepted';
  generatedAt: string;
}

// Child (student) linked to parent
export interface Child {
  _id: string;
  name: string;
  email: string;
  avatar?: string;
  enrolledCourses: Array<{ courseId: string }>;
  learningStreak?: {
    current: number;
    longest: number;
  };
}

// Child course progress
export interface ChildCourse {
  courseId: string;
  title: string;
  thumbnail?: string;
  progress: number; // 0-100
  status: 'active' | 'completed' | 'dropped';
  grade?: string;
  lastAccessed?: string;
  enrolledAt: string;
}

// Child progress statistics
export interface ChildStats {
  enrolledCoursesCount: number;
  completedCoursesCount: number;
  averageProgress: number; // 0-100
  studyTime: {
    total: number;
    weekly: Record<string, number>;
  };
  learningStreak: {
    current: number;
    longest: number;
  };
}

// Full child progress response
export interface ChildProgress {
  student: {
    name: string;
    email: string;
    avatar?: string;
  };
  stats: ChildStats;
  courses: ChildCourse[];
}

// AI Credits entry
export interface AICreditsEntry {
  amount: number;
  type: 'earned' | 'spent';
  description: string;
  createdAt: string;
}

// AI Credits response
export interface AICreditsResponse {
  student: {
    name: string;
    email: string;
  };
  aiCredits: {
    available: number;
    used: number;
    total: number;
    history: AICreditsEntry[];
  };
}

// Instructor for a child's course
export interface ChildInstructor {
  _id: string;
  name: string;
  email: string;
  avatar?: string;
  courses: Array<{
    _id: string;
    title: string;
  }>;
}

// Contact instructor request
export interface ContactInstructorRequest {
  instructorId: string;
  message?: string;
}

// Parent registration request
export interface ParentRegistrationRequest {
  name: string;
  email: string;
  password: string;
  invitationToken: string;
  numberOfChildren: number;
}

// Parent registration response
export interface ParentRegistrationResponse {
  success: boolean;
  user: {
    _id: string;
    name: string;
    email: string;
    role: 'parent';
    subscription: Subscription;
    generatedChildInvites: ChildInvite[];
  };
  token: string;
}

// Notification types including parent-specific
export type NotificationType = 
  | 'enrollment'
  | 'assignment'
  | 'quiz'
  | 'forum'
  | 'system'
  | 'course_update'
  | 'message'
  | 'announcement'
  | 'assignment_scheduled'
  | 'assignment_due'
  | 'exam_scheduled'
  | 'exam_reminder'
  | 'grade_posted'
  | 'child_activity';

// Enhanced notification interface
export interface ParentNotification {
  _id: string;
  user: string;
  fromUser?: { 
    _id: string; 
    name: string; 
    avatar?: string; 
  };
  course?: { 
    _id: string; 
    title: string; 
  };
  title: string;
  message: string;
  type: NotificationType;
  read: boolean;
  readAt?: string;
  metadata?: {
    conversationId?: string;
    announcementId?: string;
    assignmentId?: string;
    examId?: string;
    childId?: string;
    grade?: string;
    feedback?: string;
    scheduledDate?: string;
    dueDate?: string;
    duration?: number;
    preview?: string;
    priority?: string;
    [key: string]: any;
  };
  createdAt: string;
  updatedAt?: string;
}

// Notifications response with pagination
export interface NotificationsResponse {
  success: boolean;
  data: ParentNotification[];
  meta: {
    pagination: {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
    };
    unreadCount: number;
  };
}
